### ISSUE TITLE
nf-core community acknowledgements

### ISSUE THREAD

**Issue by drpatelh** [Arcadia-Science/nextflow-template#11]
Hello!

Great work on this [article](https://research.arcadiascience.com/pub/perspective-reproducible-workflows/release/2). Always nice to see an objective assessment of the current status of the field and the fact that Nextflow and Tower were your choices 💚 

Looking through this repo, I can't see any obvious acknowledgment for the nf-core template in the [main README](https://github.com/Arcadia-Science/nextflow-template#nextflow-cookiecutter-template) or for the one used in the [pipeline template](https://github.com/Arcadia-Science/nextflow-template/blob/main/%7B%7Bcookiecutter.hyphenated%7D%7D/README.md). As you know, it has taken us years of blood, sweat and tears to curate and develop this template within the community and would be awesome to have the appropriate acknowledgment. Happy to create a PR if you think this is a reasonable request.

As an aside, it would also be great to know what we could have done to improve the nf-core pipeline template to make it simpler for your use case? We are very open to making things better for the community. Not suggesting we will tick all of the boxes in terms of your requirements but feedback is always welcome!

**Comment by elizabethmcd** [comment]
Thanks for reading our pub and this suggestion! I added acknowledgements to the nf-core publication in both the main README and the pipeline template README in #12, feel free to give a look and let me know if I should add anything else.

**Comment by drpatelh** [comment]
That's perfect. Thank you!

**Comment by mertcelebi** [comment]
@drpatelh sorry it took us some time to collate the feedback, but here you go:
* I think most of our feedback boils down to two things: (1) the need for more detailed documentation and (2) a pared down version of the starter that would allow a beginner to go from `nf-core tools` to a running pipeline within minutes.
* Please feel free to ignore anything about (2) since that is not the intended use case of the tool. My understanding is that the tool is used for creating nf-core compatible pipelines to be contributed back to the organization. 
* But as an example, if I create a pipeline using `nf-core create`, add a module using `nf-core modules` and write some glue-code (and maybe a simple local module) to tie it all together, I'll potentially have to think about (1) linting, (2) params specification and (3) then validation. All of these steps are quite overwhelming to a beginner since the fixes for all happen across many directories/files. 
* In fixing these, I am not sure about:
  * What folder/file does what?
  * What is okay to modify and what isn't? As an example the `lib` directory has bunch of validation code and also `nfcore_external_java_deps.jar` and the inclusion of the latter makes me more hesitant to modify the former. 
  * In thinking about these, much of the functionality is split across multiple files (conf/, lib/, assets/ etc). This seems to be done for modularity but this level of modularity is not really needed for many early stage projects and sometimes leads to confusion as to where to address things (ie should I make the fix in `lib/WorkflowPipeline.groovy` or `lib/WorkflowMain.groovy`)?
  * How to turn on/off different linting rules? I think the documentation for this has gotten significantly better, but it was very sparse for a while. I'd rather not fully get rid of CI/linting, but would like to be able to turn it on/off easily, because they're useful eventually, not at the moment of starting a pipeline. 
  * What is happening in the `/assets` directory? Again, as a starter, why do I have to think about Microsoft Teams adaptive cards? :) For some of the functionality in `/lib` and `/assets`, I see the value of having them, but I'd rather have the option to add them on later. Not sure how easy/doable that is.

**Comment by drpatelh** [comment]
No worries! Thank you for the detailed feedback! Makes sense. I agree there is still quite a bit of bolilerplate and unobvious components in the template even after we stripped it down significantly during the transition to DSL2. We have tried to make this more controllable when creating the pipeline to strip out specific components but we haven't really gone on from there to get to a bare-bones type template. Maybe we should make a more concerted effort to do this properly.

I suspect you are already on the same page but if you think there is any mutually beneficial functionality that would be worth pushing to the template we would love to have your contributions there too!
